routes/web.php
<?php

use App\Http\Controllers\AdminPostController;
use App\Http\Controllers\NewsletterController;
use App\Http\Controllers\PostCommentsController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SessionController;
use Illuminate\Support\Facades\Route;

//HomePage
Route::get('/', [PostController::class, 'index'])->name('home');
Route::get('posts/{post:slug}', [PostController::class, 'show'])->name('home.show');

//Register
Route::get('register', [RegisterController::class, 'create'])->middleware('guest')->name('register.create');
Route::post('register', [RegisterController::class, 'store'])->middleware('guest')->name('register.store');

//Login
Route::get('login', [SessionController::class, 'create'])->middleware('guest')->name('login.create');
Route::post('login', [SessionController::class, 'store'])->middleware('guest')->name('login.store');
Route::post('logout', [SessionController::class, 'destroy'])->middleware('auth')->name('login.destroy');

//Comments
Route::post('posts/{post:slug}/comments', [PostCommentsController::class, 'store'])->name('comments.store');

//Newsletter
Route::post('newsletter', NewsletterController::class)->name('newsletter.store');

//Admin
Route::middleware('can:admin')->name('admin.')->group(function () {
	Route::resource('admin/posts', AdminPostController::class)->except('show');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	use HasFactory;

	protected $with = ['category', 'author'];

	public function scopeFilter($query, array $filters)
	{
		$query->when(
			$filters['search'] ?? false,
			function ($query, $search) {
				return $query->where('title', 'like', '%' . $search . '%')
					  ->orWhere('body', 'like', '%' . $search . '%');
			}
		);
		$query->when($filters['category'] ?? false, function ($query, $category) {
			return $query->whereHas('category', fn ($query) => $query->where('slug', $category));
		});

		$query->when($filters['author'] ?? false, function ($query, $author) {
			return $query->whereHas('author', fn ($query) => $query->where('username', $author));
		});
	}

	public function comments()
	{
		return $this->hasMany(Comment::class);
	}

	public function category()
	{
		return $this->belongsTo(Category::class);
	}

	public function author()
	{
		return $this->belongsTo(User::class, 'user_id');
	}
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;

class PostController extends Controller
{
	public function index()
	{
		return view('posts.index', [
			'posts' => Post::latest()->filter(
				request(['search', 'category', 'author'])
			)->paginate(6)->withQueryString(),
		]);
	}

	public function show(Post $post)
	{
		return view('posts.show', [
			'post' => $post,
		]);
	}
}

resources/views/admin/posts/create.blade.php
<x-layout>
    <x-setting heading="Publish New Post">
        <form method="POST" action="{{ route('admin.posts.store') }}" enctype="multipart/form-data">
            @csrf

            <x-form.input name="title" />
            <x-form.input name="slug" />
            <x-form.input name="thumbnail" type="file" />

            <x-form.textarea name="excerpt" />
            <x-form.textarea name="body" />

            <x-form.field>

                <x-form.label name="category" />
                <select name="category_id" id="category_id">

                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}"
                            {{ old('category_id') == $category->id ? 'selected' : '' }}>
                            {{ ucwords($category->name) }}</option>
                    @endforeach
                </select>
                <x-form.error name="category" />
            </x-form.field>
            <x-form.button>Publish</x-form.button>
        </form>
    </x-setting>
</x-layout>

resources/views/admin/posts/edit.blade.php
<x-layout>
    <x-setting :heading="'Edit Post: ' . $post->title">
        <form method="POST" action="{{ route('admin.posts.update', [$post->id]) }}" enctype="multipart/form-data">
            @csrf
            @method('PATCH')

            <x-form.input name="title" :value="old('title', $post->title)" required />
            <x-form.input name="slug" :value="old('slug', $post->slug)" required />

            <div class="flex mt-6">

                <div class="flex-1">
                    <x-form.input name="thumbnail" type="file" :value="old('thumbnail', $post->thumbnail)" />
                </div>
                <img src="{{ asset('storage/' . $post->thumbnail) }}" alt="" class="rounded-xl ml-6" width="100">

            </div>

            <x-form.textarea name="excerpt" required>{{ old('excerpt', $post->excerpt) }}</x-form.textarea>
            <x-form.textarea name="body" required>{{ old('body', $post->body) }}</x-form.textarea>

            <x-form.field>
                <x-form.label name="category" />
                <select name="category_id" id="category_id" required>

                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}"
                            {{ old('category_id', $post->category_id) == $category->id ? 'selected' : '' }}>
                            {{ ucwords($category->name) }}</option>
                    @endforeach

                </select>
                <x-form.error name="category" />
            </x-form.field>
            <x-form.button>Update</x-form.button>
        </form>
    </x-setting>
</x-layout>

resources/views/admin/posts/index.blade.php
<x-layout>
    <x-setting heading="Manage Posts">
        <div class="flex flex-col">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <tbody class="bg-white divide-y divide-gray-200">
                                @foreach ($posts as $post)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            <div class="flex items-center">
                                                <div class="text-sm font-medium text-gray-900">
                                                    <a href="{{ route('home.show', [$post->slug]) }}">
                                                        {{ $post->title }}
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                            <a href="{{ route('admin.posts.edit', [$post->id]) }}"
                                                class="text-blue-500 hover:text-blue-600">Edit</a>
                                        </td>

                                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                            <form method="POST"
                                                action="{{ route('admin.posts.destroy', [$post->id]) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button class="text-xs text-gray-400">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </x-setting>
</x-layout>